models/node.py
from . import ModelMixin
from . import db
from . import timestamp


class Node(db.Model, ModelMixin):
    __tablename__ = 'nodes'
    id = db.Column(db.Integer, primary_key=True)
    created_time = db.Column(db.Integer)
    name = db.Column(db.String())
    avatar = db.Column(db.String())
    introduction = db.Column(db.String())

    topics = db.relationship('Topic', backref="node", lazy='dynamic')

    def __init__(self, form):
        self.created_time = timestamp()
        self.name = form.get('nodename', '')
        self.avatar = '/static/img/default_node.png'
        self.introduction = form.get('introduction', '')

routes/node.py
from models.node import Node
from routes import *
from routes.user import current_user

from functools import wraps

main = Blueprint('node', __name__)


Model = Node


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        # print('admin required')
        if current_user().id != 1:
            # print('not admin')
            abort(404)
        return f(*args, **kwargs)
    return function


@main.route('/config')
@admin_required
def config():
    cu = current_user()
    ns = Model.query.all()
    return render_template('node/config.html', c_user=cu , nodes=ns)


@main.route('/add', methods=['POST'])
@admin_required
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.config'))


@main.route('/<int:id>')
def show(id):
    u = current_user()
    m = Model.query.get(id)
    return render_template('node/show.html', c_user=u, node=m)

routes/topic.py
from models.topic import Topic
from models.node import Node
from routes import *
from routes.user import current_user


main = Blueprint('topic', __name__)


Model = Topic


@main.route('/new')
def new():
    u = current_user()
    ns = Node.query.all()
    return render_template('topic/new.html', c_user=u, nodes=ns)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect('/')


@main.route('/<int:id>')
def show(id):
    u = current_user()
    m = Model.query.get(id)
    return render_template('topic/show.html', c_user=u, topic=m)

routes/user.py
from models.user import User
from routes import *


main = Blueprint('user', __name__)

Model = User


def current_user():
    uid = session.get('user_id')
    if uid is not None:
        u = User.query.get(uid)
        return u


# @main.route('/login_view')
# def login_view():
#     u = current_user()
#     if u is not None:
#         return redirect('/')
#     return render_template('user/login_view.html')


@main.route('/login', methods=['GET', 'POST'])
def login():
    u = current_user()
    if u is not None:
        return redirect('/')
    method = request.method
    if method == 'GET':
        msgs = None
    elif method == 'POST':
        form = request.form
        u = User(form)
        user = User.query.filter_by(username=u.username).first()
        if user is not None and user.validate_login(u):
            session['user_id'] = user.id
            return redirect('/')
        else:
            msgs = ['用户名/密码错误']
    return render_template('user/login.html', message=msgs)


@main.route('/register', methods=['GET', 'POST'])
def register():
    u = current_user()
    if u is not None:
        return redirect('/')
    method = request.method
    if method == 'GET':
        msgs = None
    elif method == 'POST':
        form = request.form
        u = User(form)
        status, msgs = u.valid()
        if status:
            u.save()
            return redirect(url_for('.login'))
    return render_template('user/register.html', message=msgs)


@main.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect('/')


@main.route('/<int:id>')
def show(id):
    cu = current_user()
    u = Model.query.get(id)
    return render_template('user/show.html', c_user=cu, user=u)


# @main.route('/register', methods=['POST'])
# def register():
#     form = request.form
#     u = User(form)
#     status, msgs = u.valid()
#     if status:
#         u.save()
#         return redirect(url_for('.login_view'))
#     else:
#         return redirect(url_for('.register_view', msgs=msgs))

templates/node/config.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block middle_left %}
    <div class="bbs-box">
        <div class="bbs-cell">
            <form action="{{ url_for('node.add') }}" method="post">
                <input type="text" name="nodename" placeholder="节点名">
                <input type="text" name="introduction" placeholder="节点简介">
                <button type="submit">添加</button>
            </form>
        </div>
        <div class="">
            {% for n in nodes %}
            <div class="bbs-cell bbs-line-top">
                {{ n.name }}
                {{ n.introduction }}
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block middle_right %}
    {{ super() }}
{% endblock %}

templates/node/show.html
{% extends "base.html" %}

{% block title %}Node - {% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block middle_left %}
    <div class="bbs-box">
        <div class="bbs-node-header clearfix">
            <img class="bbs-node-avatar wi-left" src="/static/img/node_python.png"/>
            <div class="wi-right">
                <span class="bbs-color-fade">主题总数</span>
                <span class="bbs-color-gray bbs-font-bold">{{ node.topics.count() }}</span>
            </div>
            <div class="bbs-node-title">
                <a href="/">V2EX</a> › {{ node.name }}
            </div>
            <div class="bbs-node-intro">
                {{ node.introduction }}
            </div>
        </div>
        <div class="bbs-node-topic-list">
            {% for t in node.topics %}
            <div class="bbs-node-topic-cell bbs-line-top clearfix">
                <img class="bbs-user-avatar-middle wi-left" src="{{ t.user.avatar }}" alt="" />
                <a class="bbs-node-topic-cell-count wi-right" href="{{ url_for('topic.show', id=t.id) }}">
                    {{ t.comments.count() }}
                </a>
                <a class="bbs-node-topic-cell-title" href="{{ url_for('topic.show', id=t.id) }}">{{ t.title }}</a>
                <div class="bbs-node-topic-cell-info">
                    <a href="{{ url_for('node.show', id=t.node_id) }}">{{ t.node.name }}</a>
                    <span class="bbs-color-fade">&nbsp;•&nbsp;</span>
                    <a class="bbs-font-bold" href="{{ url_for('user.show', id=t.user_id) }}">{{ t.user.username }}</a>
                    <span class="bbs-color-fade">&nbsp;•&nbsp; {{ t.created_time }}</span>
                    <!-- <span class="bbs-color-fade">&nbsp;•&nbsp; 最后回复来自</span>
                    <a class="bbs-font-bold" href="#">user1</a> -->
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block middle_right %}
    {{ super() }}
{% endblock %}