models/node.py
from . import ModelMixin
from . import db
from . import timestamp


class Node(db.Model, ModelMixin):
    __tablename__ = 'nodes'
    id = db.Column(db.Integer, primary_key=True)
    created_time = db.Column(db.Integer)
    name = db.Column(db.String())
    avatar = db.Column(db.String())
    introduction = db.Column(db.String())

    topics = db.relationship('Topic', backref="node", lazy='dynamic')

    def __init__(self, form):
        self.created_time = timestamp()
        self.name = form.get('nodename', '')
        self.avatar = '/static/img/default_node.png'
        self.introduction = form.get('introduction', '')

models/topic.py
from . import ModelMixin
from . import db
from . import timestamp


class Topic(db.Model, ModelMixin):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    created_time = db.Column(db.Integer)
    title = db.Column(db.String())
    content = db.Column(db.String())
    visit_count = db.Column(db.Integer, default=0)

    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    comments = db.relationship('Comment', backref="topic", lazy='dynamic')

    def __init__(self, form):
        self.created_time = timestamp()
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.node_id = form.get('node_id', 0)
        self.user_id = form.get('user_id', 0)

routes/node.py
from models.node import Node
from routes import *
from routes.user import current_user

from functools import wraps

main = Blueprint('node', __name__)


Model = Node


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        # print('admin required')
        if current_user().id != 1:
            # print('not admin')
            abort(404)
        return f(*args, **kwargs)
    return function


@main.route('/config')
@admin_required
def config():
    cu = current_user()
    ns = Model.query.all()
    return render_template('node/config.html', c_user=cu , nodes=ns)


@main.route('/add', methods=['POST'])
@admin_required
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.config'))


@main.route('/<int:id>')
def show(id):
    u = current_user()
    m = Model.query.get(id)
    return render_template('node/show.html', c_user=u, node=m)

routes/topic.py
from models.topic import Topic
from models.node import Node
from routes import *
from routes.user import current_user


main = Blueprint('topic', __name__)


Model = Topic


@main.route('/new')
def new():
    u = current_user()
    ns = Node.query.all()
    return render_template('topic/new.html', c_user=u, nodes=ns)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect('/')


@main.route('/<int:id>')
def show(id):
    u = current_user()
    m = Model.query.get(id)
    return render_template('topic/show.html', c_user=u, topic=m)

routes/user.py
from models.user import User
from routes import *


main = Blueprint('user', __name__)

Model = User


def current_user():
    uid = session.get('user_id')
    if uid is not None:
        u = User.query.get(uid)
        return u


# @main.route('/login_view')
# def login_view():
#     u = current_user()
#     if u is not None:
#         return redirect('/')
#     return render_template('user/login_view.html')


@main.route('/login', methods=['GET', 'POST'])
def login():
    u = current_user()
    if u is not None:
        return redirect('/')
    method = request.method
    if method == 'GET':
        msgs = None
    elif method == 'POST':
        form = request.form
        u = User(form)
        user = User.query.filter_by(username=u.username).first()
        if user is not None and user.validate_login(u):
            session['user_id'] = user.id
            return redirect('/')
        else:
            msgs = ['用户名/密码错误']
    return render_template('user/login.html', message=msgs)


@main.route('/register', methods=['GET', 'POST'])
def register():
    u = current_user()
    if u is not None:
        return redirect('/')
    method = request.method
    if method == 'GET':
        msgs = None
    elif method == 'POST':
        form = request.form
        u = User(form)
        status, msgs = u.valid()
        if status:
            u.save()
            return redirect(url_for('.login'))
    return render_template('user/register.html', message=msgs)


@main.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect('/')


@main.route('/<int:id>')
def show(id):
    cu = current_user()
    u = Model.query.get(id)
    return render_template('user/show.html', c_user=cu, user=u)


# @main.route('/register', methods=['POST'])
# def register():
#     form = request.form
#     u = User(form)
#     status, msgs = u.valid()
#     if status:
#         u.save()
#         return redirect(url_for('.login_view'))
#     else:
#         return redirect(url_for('.register_view', msgs=msgs))

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}WI</title>
        <link rel="stylesheet" href="/static/css/bbs.css">
        <link rel="icon" href="/static/img/icon.png">
        {% endblock %}
    </head>
    <body>
        {% block top %}
        <div class="bbs-top">
            <div class="bbs-top-content bbs-content-size clearfix">
                <a class="bbs-top-logo wi-left" href="/" title='way to explore'></a>
                <input class="bbs-top-search wi-left" type="text" name="search" placeholder="施工中">
                <div class="bbs-top-nav wi-right">
                    <a href="/">首页</a>
                    {% if c_user %}
                        <a href="{{ url_for('user.show', id=c_user.id) }}">{{ c_user.username }}</a>
                        <a href="{{ url_for('user.logout') }}">登出</a>
                    {% else %}
                        <a href="{{ url_for('user.register') }}">注册</a>
                        <a href="{{ url_for('user.login') }}">登录</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endblock %}

        <div class="bbs-middle">
            <div class="bbs-middle-content bbs-content-size wi-flex">
                <div class="bbs-middle-content-left wi-2">
                    {% block middle_left %}
                    {% endblock %}
                </div>
                <div class="bbs-middle-content-right wi-1">
                    {% block middle_right %}
                    <div class="bbs-box">
                        {% if c_user %}
                            <div class="bbs-cell clearfix">
                                <img class="bbs-user-avatar-middle wi-left" src="{{ c_user.avatar }}" alt="" />
                                <a class="bbs-username" href="{{ url_for('user.show', id=c_user.id) }}">{{ c_user.username }}</a>
                            </div>
                            <div class="bbs-cell bbs-line-top bbs-text-center">
                                <a href="{{ url_for('topic.new') }}">创作新主题</a>
                            </div>
                        {% else %}
                            <div class="bbs-cell">
                                <strong>V2EX = way to explore</strong>
                                <div class="bbs-color-fade">
                                    V2EX 是一个关于分享和探索的地方
                                </div>
                            </div>
                            <div class="bbs-cell bbs-line-top bbs-text-center">
                            <a href="{{ url_for('user.register') }}">
                                <button type="button">现在注册</button>
                            </a>
                            <div class="bbs-cell">
                                已注册用户请 <a href="{{ url_for('user.login') }}">登录</a>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                    {% endblock %}
                </div>
            </div>
        </div>

        {% block bottom %}
        <div class="bbs-bottom">
            <div class="bbs-bottom-content bbs-content-size">
                <div class="bbs-bottom-nav">
                    <a href="#">关于</a>
                    <span>&nbsp;·&nbsp;</span>
                    <a href="#">FAQ</a>
                    <span>&nbsp;·&nbsp;</span>
                    <a href="#">鸣谢</a>
                    <span>&nbsp;·&nbsp;</span>
                    <a href="#">7人在线</a>
                </div>
                <div class="bbs-bottom-about">
                    创意工作者们的社区<br>World is powered by solitude
                </div>
            </div>
        </div>
        {% endblock %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block middle_left %}
    <div class="bbs-box">
        <div class="bbs-node-nav">
            <span class="bbs-node-nav-active">全部</span>
            {% for n in nodes %}
            <a href="{{ url_for('node.show', id=n.id) }}">{{ n.name }}</a>
            {% endfor %}
        </div>
        <div class="bbs-node-topic-list">
            {% for t in topics %}
            <div class="bbs-node-topic-cell bbs-line-top clearfix">
                <img class="bbs-user-avatar-middle wi-left" src="{{ t.user.avatar }}" alt="" />
                <a class="bbs-node-topic-cell-count wi-right" href="{{ url_for('topic.show', id=t.id) }}">
                    {{ t.comments.count() }}
                </a>
                <a class="bbs-node-topic-cell-title" href="{{ url_for('topic.show', id=t.id) }}">{{ t.title }}</a>
                <div class="bbs-node-topic-cell-info">
                    <a href="{{ url_for('node.show', id=t.node_id) }}">{{ t.node.name }}</a>
                    <span class="bbs-color-fade">&nbsp;•&nbsp;</span>
                    <a class="bbs-font-bold" href="{{ url_for('user.show', id=t.user_id) }}">{{ t.user.username }}</a>
                    <span class="bbs-color-fade">&nbsp;•&nbsp;{{ t.created_time }}</span>
                    <!-- <span class="bbs-color-fade">&nbsp;•&nbsp; 最后回复来自</span>
                    <a class="bbs-font-bold" href="#">user1</a> -->
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="bbs-box">

    </div>
{% endblock %}

{% block middle_right %}
    {{ super() }}
{% endblock %}

templates/node_view.html
{% extends "base.html" %}

{% block title %}Node - {% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block middle_left %}
    <div class="bbs-box">
        <div class="bbs-node-header clearfix">
            <img class="bbs-node-avatar wi-left" src="/static/img/node_python.png"/>
            <div class="wi-right">
                <span class="bbs-color-fade">主题总数</span>
                <span class="bbs-color-gray bbs-font-bold">5711</span>
            </div>
            <div class="bbs-node-title">
                <a href="#">V2EX</a> › Node名
            </div>
            <div class="bbs-node-intro">
                这里讨论各种 Python 语言编程话题，也包括 Django，Tornado 等框架的讨论。这里是一个能够帮助你解决实际问题的地方。
            </div>

        </div>
        <div class="bbs-node-topic-list">
            <div class="bbs-node-topic-cell bbs-line-top clearfix">
                <img class="bbs-user-avatar-big wi-left" src="/static/img/user1.png" alt="" />
                <a class="bbs-node-topic-cell-count wi-right" href="#">
                    17
                </a>
                <a class="bbs-node-topic-cell-title" href="#">简单的利用 Logistic 训练的因子模型 年化超额 alpha 超过 20%</a>
                <div class="bbs-node-topic-cell-info">
                    <a class="bbs-font-bold" href="#">user</a>
                    <span class="bbs-color-fade">&nbsp;•&nbsp; time</span>
                    <span class="bbs-color-fade">&nbsp;•&nbsp; 最后回复来自</span>
                    <a class="bbs-font-bold" href="#">user1</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block middle_right %}
    {{ super() }}
{% endblock %}

templates/topic_view.html
{% extends "base.html" %}

{% block title %}Topic - {% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block middle_left %}
    <div class="bbs-box">
        <div class="bbs-topic-header clearfix">
            <img class="bbs-user-avatar-large wi-right" src="/static/img/user1.png" />
            <div class="bbs-topic-link">
                <a href="#">V2EX</a> › <a href="#">Node名</a>
            </div>
            <div class="bbs-topic-title">
                python 命令为何无法在 cmd 直接执行？
            </div>
            <div class="bbs-topic-info bbs-color-gray">
                <a href="#">user</a>
                <span> · 9 小时 42 分钟前用 iPhone 发布 · </span>
                <span>1071次点击</span>
            </div>
        </div>
        <div class="bbs-topic-content bbs-cell bbs-line-top">
            win10 64 位之前装 3.5.2 的时候勾选 path ，可以直接运行。
            卸载之后安装 3.4.4 ，就提示无法运行应用（非无效命令），再装回 3.5.2 也一样不行了，也添加过环境变量一样不行。 但是管理员模式运行可以。
        </div>
    </div>
    <div class="bbs-box bbs-margin-top">
        <div class="">

        </div>
        回复
    </div>
{% endblock %}

{% block middle_right %}
    {{ super() }}
{% endblock %}