models/topic.py
from . import ModelMixin
from . import db
from . import timestamp


class Topic(db.Model, ModelMixin):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    created_time = db.Column(db.Integer)
    title = db.Column(db.String())
    content = db.Column(db.String())
    visit_count = db.Column(db.Integer, default=0)

    node_id = db.Column(db.Integer, db.ForeignKey('nodes.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    comments = db.relationship('Comment', backref="topic", lazy='dynamic')

    def __init__(self, form):
        self.created_time = timestamp()
        self.title = form.get('title', '')
        self.content = form.get('content', '')
        self.node_id = form.get('node_id', 0)
        self.user_id = form.get('user_id', 0)

routes/comment.py
from models.comment import Comment
from models.node import Node
from routes import *
from routes.user import current_user


main = Blueprint('comment', __name__)


Model = Comment


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('topic.show', id=m.topic_id))

routes/node.py
from models.node import Node
from routes import *
from routes.user import current_user

from functools import wraps

main = Blueprint('node', __name__)


Model = Node


def admin_required(f):
    @wraps(f)
    def function(*args, **kwargs):
        # print('admin required')
        if current_user().id != 1:
            # print('not admin')
            abort(404)
        return f(*args, **kwargs)
    return function


@main.route('/config')
@admin_required
def config():
    cu = current_user()
    ns = Model.query.all()
    return render_template('node/config.html', c_user=cu , nodes=ns)


@main.route('/add', methods=['POST'])
@admin_required
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect(url_for('.config'))


@main.route('/<int:id>')
def show(id):
    u = current_user()
    m = Model.query.get(id)
    return render_template('node/show.html', c_user=u, node=m)

routes/topic.py
from models.topic import Topic
from models.node import Node
from routes import *
from routes.user import current_user


main = Blueprint('topic', __name__)


Model = Topic


@main.route('/new')
def new():
    u = current_user()
    ns = Node.query.all()
    return render_template('topic/new.html', c_user=u, nodes=ns)


@main.route('/add', methods=['POST'])
def add():
    form = request.form
    m = Model(form)
    m.save()
    return redirect('/')


@main.route('/<int:id>')
def show(id):
    u = current_user()
    m = Model.query.get(id)
    return render_template('topic/show.html', c_user=u, topic=m)

routes/user.py
from models.user import User
from routes import *


main = Blueprint('user', __name__)

Model = User


def current_user():
    uid = session.get('user_id')
    if uid is not None:
        u = User.query.get(uid)
        return u


# @main.route('/login_view')
# def login_view():
#     u = current_user()
#     if u is not None:
#         return redirect('/')
#     return render_template('user/login_view.html')


@main.route('/login', methods=['GET', 'POST'])
def login():
    u = current_user()
    if u is not None:
        return redirect('/')
    method = request.method
    if method == 'GET':
        msgs = None
    elif method == 'POST':
        form = request.form
        u = User(form)
        user = User.query.filter_by(username=u.username).first()
        if user is not None and user.validate_login(u):
            session['user_id'] = user.id
            return redirect('/')
        else:
            msgs = ['用户名/密码错误']
    return render_template('user/login.html', message=msgs)


@main.route('/register', methods=['GET', 'POST'])
def register():
    u = current_user()
    if u is not None:
        return redirect('/')
    method = request.method
    if method == 'GET':
        msgs = None
    elif method == 'POST':
        form = request.form
        u = User(form)
        status, msgs = u.valid()
        if status:
            u.save()
            return redirect(url_for('.login'))
    return render_template('user/register.html', message=msgs)


@main.route('/logout')
def logout():
    session.pop('user_id', None)
    return redirect('/')


@main.route('/<int:id>')
def show(id):
    cu = current_user()
    u = Model.query.get(id)
    return render_template('user/show.html', c_user=cu, user=u)


# @main.route('/register', methods=['POST'])
# def register():
#     form = request.form
#     u = User(form)
#     status, msgs = u.valid()
#     if status:
#         u.save()
#         return redirect(url_for('.login_view'))
#     else:
#         return redirect(url_for('.register_view', msgs=msgs))

templates/topic/new.html
{% extends "base.html" %}

{% block title %}新主题 - {% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block middle_left %}
    <div class="bbs-box">
        <div class="bbs-topic-new">
            <form class="" action="{{ url_for('topic.add') }}" method="post">
                <input class="wi-hide" type="text" name="user_id" value="{{ c_user.id }}">
                <input type="text" name="title" placeholder="标题" required="required">
                <input type="text" name="content" placeholder="内容" required="required">
                <select name="node_id">
                    {% for n in nodes %}
                    <option value="{{ n.id }}">{{ n.name }}</option>
                    {% endfor %}
                </select>
                <button type="submit" name="button">创建新主题</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block middle_right %}
    {{ super() }}
{% endblock %}

templates/topic/show.html
{% extends "base.html" %}

{% block title %}Topic - {% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block middle_left %}
    <div class="bbs-box">
        <div class="bbs-topic-header clearfix">
            <img class="bbs-user-avatar-large wi-right" src="{{ topic.user.avatar }}" />
            <div class="bbs-topic-link">
                <a href="/">V2EX</a> › <a href="{{url_for('node.show', id=topic.node_id)}}">{{ topic.node.name }}</a>
            </div>
            <div class="bbs-topic-title">
                {{ topic.title }}
            </div>
            <div class="bbs-topic-info bbs-color-gray">
                <a href="{{ url_for('user.show', id=topic.user_id) }}">{{ topic.user.username }}</a>
                <span> · {{ topic.created_time }} · </span>
                <span>1071次点击</span>
            </div>
        </div>
        <div class="bbs-topic-content bbs-cell bbs-line-top">
            {{ topic.content }}
        </div>
    </div>
    {% if topic.comments.count() > 0 %}
    <div class="bbs-box bbs-margin-top">
        <div class="bbs-color-gray bbs-cell">
            {{ topic.comments.count() }}回复 &nbsp;|&nbsp; 直到{{ topic.comments[-1].created_time }}
        </div>
        {% for m in topic.comments %}
        <div class="bbs-comment-cell bbs-cell bbs-line-top clearfix">
            <img class="bbs-user-avatar-middle wi-left" src="{{ m.user.avatar }}" alt="" />
            <div class="bbs-comment-no wi-right">
                {{ loop.index }}
            </div>
            <div class="bbs-comment-info">
                <a class="bbs-font-bold" href="{{ url_for('user.show', id=m.user_id) }}">{{ m.user.username }}</a>
                <span class="bbs-color-fade">&nbsp; {{ m.created_time }}</span>
            </div>
            <div class="bbs-comment-content">
                {{ m.content }}
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="bbs-comment-empty bbs-margin-top">
        目前尚无回复
    </div>
    {% endif %}
    {% if c_user %}
    <div class="bbs-box bbs-margin-top">
        <div class="bbs-cell">
            添加一条新回复
        </div>
        <div class="bbs-cell bbs-line-top">
            <form action="{{ url_for('comment.add') }}" method="post">
                <input class="wi-hide" type="text" name="user_id" value="{{ c_user.id }}">
                <input class="wi-hide" type="text" name="topic_id" value="{{ topic.id }}">
                <input type="text" name="content" placeholder="内容">
                <button type="submit" name="button">回复</button>
            </form>
        </div>
    </div>
    {% endif %}
{% endblock %}

{% block middle_right %}
    {{ super() }}
{% endblock %}